name: devops-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Configuração inicial pipeline"		
  acceptance:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo "Estágio acceptance"    
  Trabalho_Automação:
   runs-on: ubuntu-latest
   needs: acceptance
   steps:
   - run: echo "Estágio acceptance"   
  infra:
    runs-on: ubuntu-latest
    needs: Trabalho_Automação
    steps:
    - run: echo "Estágio acceptance"
