name: devops-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
    needs: build
    steps:
    run: echo "Estágio acceptance"
    runs-on: ubuntu-latest
    needs: acceptance
    steps:
    - run: echo "Estágio release"
  


