name: teste-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Configuração inicial do pipeline"		
  Validando_Pontuacao:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Estágio acceptance"
  Pontuacao_menor_62 :
   runs-on: ubuntu-latest
   needs: Validando_Pontuacao
   steps:
     - run: echo "Estágio release"
   Cruzeiro_não_vai_Subir :
    runs-on: ubuntu-latest
    needs: Pontuacao_menor_62 :
    steps:
     - run: echo "Estágio release"
