name: devops-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Configuração inicial do pipeline"
        
acceptance:
runs-on: ubuntu-latest
needs: buil
steps:
run: echo "Estágio acceptnce"


