name: devops-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Configuração inicial do pipeline"
        
jobs:
build:        
acceptance:
runs-on: ubuntu-latest
steps:
- run: echo "Estágio acceptnce"

release:
runs-on: ubuntu-latest
needs: acceptance
steps:
- run: echo " Estágio release"

