name: teste-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Configuração inicial do pipeline"		
  Validando Pontuação:
    runs-on: ubuntu-latest
    needs: build
    steps:    
      - run: echo "Estágio acceptance"
 Cruzeiro:
   runs-on: ubuntu-latest
   needs: Validando Pontuação
   steps:
    - run: echo "Estágio release"
